### PR TITLE
Feature/development tools

### PR DESCRIPTION
**Pull request by tomvik**
### What does this PR do?

- Adds the dependencies for eslint and flow checks
- Adds documentation to README to install and use the previous mentioned checks
- Configures vscode for some automatic checks and fixes
- Fixes App.js to follow eslint and flow standard

#### Related issues

#10 

#### Merge Checklist:

- [x] The branch is up-to-date (i.e. rebased) with the base branch
- [x] No code style issues

### CODE REVIEW

**Comment by tomvik** [comment]
Having some issues with the eslint version

**Review by RicardoChapaRomero — APPROVED** [review]
LGTM! Great work with the documentation

**Comment by tomvik** [comment]
@RicardoChapaRomero this should be ready for review.

I've tested it in npm, yarn, and with docker. It's as simple as to install the packages :) and to run the checks, I think the README is clear enough

**Comment by tomvik** [comment]
I checked everything, it's all good. The eslint erros that we still got during the presentation today were unfixable by eslint. ie. name of variables or type of variables.

**Review by RicardoChapaRomero — APPROVED** [review]
LGTM!

**Pull request merged**
