### PR TITLE
Feature/support us types

### PR DESCRIPTION
**Pull request by AuroTB**
# What does this PR do?

## General changes:
- Implements Support Us [new design](https://www.canva.com/design/DAETkwpfxvE/JyB-od1UPqjVd2vj06DZUg/view?website#2)
- Change the "contact" page to "Support Us" (path, footer, and navbar)
- Adds sticky translating button which translates all web page
- Eliminates unnecessary code and components (tests)
- Updates info (packages, main projects)

## Header
- "Contact us" button leads to formulary

## Support us types component
- responsive (vertical and horizontal view)
- clickable
- fading effect

## Sponsor packages
- animation when hovering
- responsivity ()
- contact us button

## Contact us forms
- validates all textfields are filled when submitted (turns red and shows helper text if not)
- Creates mail params
- responsive

#### Related issues

#109 

#### Merge Checklist:

- [x] The branch is up-to-date (i.e. rebased) with the base branch
- [x] No code style issues (eslint and flow)

### CODE REVIEW

**Comment by JFPach98** [comment]
In src/components/SupportUs/SupportUs.css, consider changing the attribute position to other than fixed or to change the position of the element, since it overlaps with text and images of the sponsor types section.
image

**Comment by JFPach98** [comment]
This part of the support us sub page does not get translated when the en/es button is clicked. However, it could be solved in a different issue.

image

**Review by JFPach98 — CHANGES_REQUESTED** [review]
Overall, I think it is alright, I would just suggest to change the position of the translation button.

**Comment by JFPach98** [comment]
Responsivity issue is solved, however I'll continue to work in it, to avoid merging issues

**Review by JFPach98 — COMMENTED** [review]
The responsivity issue was solved

**Comment by JFPach98** [comment]
In your last commit, you modified the size of the cards that contains the packages, which leave them a little bit awkward looking, as in this image:
image

Could you please revert it back to its previous size?

**Comment by AuroTB** [comment]
> This part of the support us sub page does not get translated when the en/es button is clicked. However, it could be solved in a different issue.
> 
> image

Are you talking about "Support Us" in the navbar?

**Comment by AuroTB** [comment]
> In your last commit, you modified the size of the cards that contains the packages, which leave them a little bit awkward looking, as in this image:
> image
> 
> Could you please revert it back to its previous size?

they are the same size, can you please provide the screen dimensions?

**Review by JFPach98 — APPROVED** [review]
Everything looks fine now

**Review by JFPach98 — APPROVED** [review]
Looks fine

**Pull request merged**
