### PR TITLE
Feature/unit test/home

### PR DESCRIPTION
**Pull request by JamirLeal**
### What does this PR do?

- This PR corrects all @flow code style issues, also unit test jest files are added for all /Home components.

#### Related issues

#28 

#### Merge Checklist:

- [ ] The branch is up-to-date (i.e. rebased) with the base branch
- [ ] No code style issues

### CODE REVIEW

**Comment by tomvik** [comment]
@JamirLeal 

Add `// $FlowFixMe` in the previous line of 
image

For:
image

Check that it is inside an if checking that the object is not null

This means that something is wrong with the typing:
image

**Comment by tomvik** [comment]
@JamirLeal Remember that you can run the check on your computer, it could make your development process faster.

**Comment by JamirLeal** [comment]
Thank you for the comments @tomvik!

**Review by RicardoChapaRomero — APPROVED** [review]
LGTM! I left some minor comments

**Pull request merged**
